/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.skilldistillery.tat;

import org.junit.Test;
import static org.junit.Assert.*;

import java.util.List;

public class TrelloCsvFileTests {

	@Test
	public void testTrelloCsvFileReturnsSomeTopics() {
		TrelloCsvFile myCsvFile = new TrelloCsvFile("SD16_Unit1.csv");
		List<Topic> myTopics = myCsvFile.getTopics();
		assertTrue(myTopics.size() > 0);
	}

}
